### ISSUE TITLE
what the freak?!@?!#!?#

### ISSUE THREAD

**Issue by sirvon** [antonvmironov/FunctionalConcurrency#2]
maybe i'm too hyper but on first glance
this looks like the most complete usable
async reactive library for swift/ios
looks wise and feel wise without even touching
the code!!!!

thank you !!

**Comment by antonvmironov** [comment]
Thank you for your cheerful feedback!
Messages like these inspire me to improve continuously.

**Comment by igor9silva** [comment]
Any other feedback after this period @sirvon?
I'll be using this in production.

**Comment by antonvmironov** [comment]
@igor9silva I've shared products that I know using AsyncNinja in production at [known_users](https://github.com/AsyncNinja/AsyncNinja/blob/master/known_users.md). Maybe it would help you to decide.
