### ISSUE TITLE
Analog of signal

### ISSUE THREAD

**Issue by krupin-maxim** [antonvmironov/FunctionalConcurrency#3]
Which of primitives in your project I can use for simple signal like in ReactiveCocoa? I want to just send events in one place and receive them in another place.

**Comment by antonvmironov** [comment]
Hello @krupin-maxim. There is a `Channel<Update, Success>` primitive that provides event stream behavior.

`Channel<Update, Success>` is a generic class that must be specialized with 2 types: `Update` and `Success`.

* `Update` is a type for update events. This kind of events can appear multiple times.
* `Success` is used for completion events. Actual kind of completion event is `Fallible<Success>`, wehere `Fallible<T>` is a validation monad in AsyncNinja. This kind of events can appear once through `Channel` lifecycle. This event completes the channel. No more events will occur after that.

There are two ways of creating `Channel` in AsyncNinja.

### option 1: use `Producer` primitive

```swift
func countTo100() -> Channel<Int, String> {
	let producer = Producer<Int, String>() // make producer

	DispatchQueue.global().async {
		for i in 0...100 {
			producer.update(i)  // puts update event to the producer
		}

		// Use Producer<Update, Success>.fail(_ failure: Error) if you want producer to fail
		// producer.fail(MyError.somethingIsWrong)
	
		// Use Producer<Update, Success>.success(_ success: Success) if you want producer to succeed
		producer.succeed("I'm done!")  // puts completion (success) event to the channel with provided value
	}
	
	return producer // `Producer` is a subclass of `Channel`
}
```

### option 2: use `func channel(executor: Executor, block: ((Update) -> Void) -> Void) -> Channel<Update, Success>`

```swift
func countTo100() -> Channel<Int, String> {
	return channel(executor: .background) { (update: (Update) -> Void) -> Success in
		for i in 0...100 {
			update(i) // puts update event to the channel with provided value
		}
		
		// Thrown an `Error` if you want channel to fail
		// throw MyError.somethingIsWrong 
		
		// return `Success` value if you want channel to succeed
		return "I'm done!"
	}
}
```

### usage of `Channel`
There are many ways of using `Channel`. Starting from `onUpdate` to observe events up to most of operations described at [RxMarbles](http://rxmarbles.com).

```swift
countTo100()
	.map { (number: Int) -> String in
		return "\(number)%"
	}
	.onUpdate { (percentage: String) in
		print(percentage)
	}
	.onSuccess { (successMessage: String) in
		print(successMassage)
	}
	.onFailure { (failure: Error) in
		print("Failure: \(failure)")
	}
```

Thanks for the question.
