### ISSUE TITLE
Swift 4 exclusive memory access enforcement

### ISSUE THREAD

**Issue by nezhyborets** [antonvmironov/FunctionalConcurrency#5]
Hi!

As you know, Swift 4 introduces Exclusive Memory Access Enforcement, which gives us some kinds of issues when using `SpinLockLocking` and `UnfairLockLocking` structs under Locking protocol. Is there a reason to use `struct` for these types? Or it may be changed to `class` to avoid Thread Sanitizer errors? Thanks!

![screen shot 2018-06-18 at 12 44 01 pm](https://user-images.githubusercontent.com/2803931/41529527-2aa5c15c-72f6-11e8-829d-4129ea69518e.png)
![screen shot 2018-06-18 at 12 50 49 pm](https://user-images.githubusercontent.com/2803931/41529560-41e8b6f8-72f6-11e8-9e6f-c9e0af1dc005.png)

**Comment by antonvmironov** [comment]
Hi, @nezhyborets . Thanks for report!

I do not mind to change that but I have to make sure those changes would have desired effect. What Xcode version are you using? Exclusive memory access checks could behave differently depending on swift toolset used.

I want to start with making a unit test that would test such behavior.

**Comment by antonvmironov** [comment]
Hi, @nezhyborets. I've been able to reproduce the issue with tests. Could you please double check if it is reproducible with latest master?

**Comment by nezhyborets** [comment]
I don't see that issue anymore. Thanks!
